name: Rain Alert Automation

on:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 8:00 AM UTC
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run-rain-alert:
    runs-on: ubuntu-latest
    environment: Weather

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Specify the version of Python you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Rain Alert Script
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          MY_LAT: ${{ secrets.MY_LAT }}
          MY_LONG: ${{ secrets.MY_LONG }}
          OWM_APP_ID: ${{ secrets.OWM_APP_ID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        run: python main.py # Replace with the name of the main script in your repo
